name: E2E Test Check
on:
  pull_request:
    types: ['opened', 'synchronize']
    paths:
      - '.github/**'
      - '.github/workflows/**'
      - 'quickstarts/**'

jobs:
  e2e-check:
    runs-on: terraform-alicloud-landing
    environment:
      name: acctests
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v34
        with:
          dir_names: "true"
          separator: ","
          files: "quickstarts/*"
          files_ignore: "**/TestRecord.md"
          dir_names_max_depth: 2
      - name: test pr
        run: |
          folders="${{ steps.changed-files.outputs.all_changed_files }}"
          for f in ${folders//,/ }
          do
            f=$(echo $f | xargs echo -n)
            echo "===> Terraform testing in" $f
            terraform -chdir=$f init -upgrade
            cp scripts/plan.tftest.hcl $f/
            terraform -chdir=$f test test -verbose
            if [[ $? -ne 0 ]]; then
              echo -e "\033[31m[ERROR]\033[0m: running terraform test for plan failed."
              #exit 1
            else
              rm -rf scripts/plan.tftest.hcl
              cp scripts/apply.tftest.hcl $f/
              terraform -chdir=$f test test
              if [[ $? -ne 0 ]]; then
                echo -e "\033[31m[ERROR]\033[0m: running terraform test for apply failed."
                #exit 1
              fi
              rm -rf scripts/apply.tftest.hcl
            fi
          done
