name: Pull Request Checks

on:
  pull_request:
    branches:
      - master
      - main
    types: [ 'opened', 'synchronize' ]
    paths:
      - '.github/**'
      - '.github/workflows/**'
      - 'quickstarts/**'

jobs:
  terrafmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "GO_VERSION=$(cat .go-version)" >> $GITHUB_ENV
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v34
        with:
          dir_names: "true"
          separator: ","
          files: "quickstarts/*"
          dir_names_max_depth: 2
      - name: terrafmt
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          go install github.com/katbyte/terrafmt@latest
          folders=${{ steps.changed-files.outputs.all_changed_files }}
          for f in ${folders//,/ }
          do
          	f=$(echo $f | xargs echo -n)
            (echo "===> Terrafmt diff checking in" $f && terrafmt diff $f --check) || error=true
            if ${error}; then
               echo -e "\033[1m[ERROR]\033[0m: Some quickstarts codes has not been formated, and please running terraform fmt --recursive command before pushing."
               exit 1
            fi
          done

  pre-pr-check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v34
        with:
          dir_names: "true"
          separator: ","
          files: "quickstarts/*"
          dir_names_max_depth: 2
      - name: pr-check
        run: |
          CHANGED_FOLDERS="${{ steps.changed-files.outputs.all_changed_files }}"
          if [ -z "${{ github.event.number }}" ]; then
            CHANGED_FOLDERS=$(find ./quickstarts -maxdepth 1 -mindepth 1 -type d | tr '\n' ',')
          fi
          if [ ! -f /usr/local/bin/terraform ]; then
            wget -q https://releases.hashicorp.com/terraform/1.6.0/terraform_1.6.0_linux_amd64.zip
            unzip terraform_1.6.0_linux_amd64.zip -d /usr/local/bin/
          fi
          sh scripts/terraform-validate.sh CHANGED_FOLDERS=${CHANGED_FOLDERS}
