name: Weekly E2E Test Check
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'
      
    
jobs:
  all-e2e-test:
    if: github.repository_owner == 'alibabacloud-automation'
    name: 'weekly e2e check'
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: set id
        id: set-job-id
        uses: ayachensiyuan/get-action-job-id@v1.6
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          job-name: 'weekly e2e check'   
      - name: get pull request info
        run: |
          echo "repo name is" ${{github.event.pull_request.head.repo.full_name}}
          echo "branch is" ${{github.event.pull_request.head.ref}}
          echo "the current job id is ${{ steps.set-job-id.outputs.jobId }}"
      - name: weekly e2e test
        run: |
          objectPath="github-action/${{github.repository}}/weekly-e2e/Action-${{github.run_number}}-${{github.run_id}}-${{ steps.set-job-id.outputs.jobId }}"
          curl -H "X-Fc-Invocation-Type:Async" -s https://example-ci-terrafoodule-ci-svrrwvrpnj.ap-southeast-1.fcapp.run/?branch=main\&repo_name=${{github.repository}}\&oss_object_path=${objectPath}